integer comchr,
        tabchr,
        ubchr,
        fill,
        adjust,
        numtyp,
        lsval,
        inval,
        llval,
        tival,
        poval,
        ceval,
        ulval,
        litval,
        blval,
        skpval,
        tabpos
common /cparam/comchr,tabchr,ubchr,fill,adjust,numtyp,lsval,inval,
        llval,tival,poval,ceval,ulval,litval,blval,skpval,tabpos(MAXTABS)
